blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/your-username/vibecode-terminal/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://docs.vibecode.com
    about: Check our documentation for detailed guides and API references.
  - name: Security Issues
    url: https://github.com/your-username/vibecode-terminal/security/advisories/new
    about: Please report security vulnerabilities privately.